/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-12-07 12:17:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.authentication;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import blood.dto.*;
import blood.bl.*;
import blood.dl.*;
import blood.utlity.*;
import java.sql.Date;
import java.text.SimpleDateFormat;

public final class direct_005fdonor_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
      String message=""; 
  	  String donor_login_id;
	  DonorLoginDTO user1=null;
	  DonorLoginDTO user2=null;
	  String donor_password;
  
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Donor Login</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<title>User Login</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\t\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" href=\"images/icons/favicon.ico\"/>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/iconic/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-login100\" style=\"background-image: url('images/logo12.png');\">\r\n");
      out.write("\t\t<div class=\"wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30\">\r\n");
      out.write("\t\r\n");
      out.write("<form action=\"direct_donor_login.jsp\" method=\"post\">\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("  ");
      out.write("               \r\n");
      out.write("   <td height=\"33\" align=\"center\" valign=\"middle\" style=\"color: #F70509\">\r\n");
      out.write("   ");

                   if(request.getParameter("submit")!=null)
                   {
                	   donor_login_id=request.getParameter("txt_user_id") ;
                	  donor_password=request.getParameter("txt_password");
                	  user1=new DonorLoginDTO();

                	  user1.setDonor_login_id(donor_login_id);  
                	  user1.setDonor_password(donor_password);
                	  //session.setAttribute("donor_login_id", donor_login_id);
                	  user2=DonorLoginBL.validateUser(user1);
                	  if(user2!=null)
                	  {
                		 // session.setAttribute("user_name", user2.getDonor_password());
                		  session.setAttribute("donorId", user2.getDonor_login_id());
                		  response.sendRedirect("../Blood/welcome_donor.jsp");
                	  }
                	  else
                	  {
                		  message="wrong userID or password";
                		  
                	  }
                   }
   
      out.write("\r\n");
      out.write("   \t\t\t      ");
      out.print(message );
      out.write("\r\n");
      out.write("      \r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<span class=\"login100-form-title p-b-37\">\r\n");
      out.write("\t\t\t\t\tUser Login\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"wrap-input100 validate-input m-b-20\">\r\n");
      out.write("    <label for=\"uname\"><b>UserId</b></label><br>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter UserID\" name=\"txt_user_id\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"psw\"><b>Password</b></label><br>\r\n");
      out.write("    <input type=\"password\" placeholder=\"Enter Password\" name=\"txt_password\" required><br><br>\r\n");
      out.write("      \r\n");
      out.write("    <div class=\"container-login100-form-btn\">  \r\n");
      out.write("    <input class=\"login100-form-btn\" type=\"submit\" value=\"Login\" name=\"submit\"><br><br><br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   \t<div class=\"text-center\">\r\n");
      out.write("\t<a href=\"../Blood/donor_add.jsp\" class=\"txt2 hov1\">\r\n");
      out.write("\tSign Up\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</div><br>\r\n");
      out.write("   \r\n");
      out.write("   \t<div class=\"text-center\">\r\n");
      out.write("\t<a href=\"../Designs/index.jsp\" class=\"txt2 hov1\">\r\n");
      out.write("\tBack to Home Page\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
